repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6  # Specify the version of Ruff you want to use
    hooks:
      - id: ruff
        args: [ --fix ]  # Enable auto-fixes by Ruff
      - id: ruff-format
