name: Lint with Ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .
